spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # public
    url: jdbc:mysql://book-rds.c45lwe54ntds.ap-northeast-2.rds.amazonaws.com:3306/book?serverTimezone=Asia/Seoul
    # private
    #    url: jdbc:mysql://book-db-mysql.c45lwe54ntds.ap-northeast-2.rds.amazonaws.com:3306/book?serverTimezone=Asia/Seoul
    username: admin
    password: mysqladmin

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  thymeleaf:
    cache: false
